### ISSUE TITLE
Display an activity

### ISSUE THREAD

**Issue by OndrejJarina** [AIR-FOI-HR/AIR19E1#10]
A screen with information about activity, contact to the creator and a button to sign up.

**Comment by pablomf97** [comment]
**In review**: check these two commits to review it:
- [Added venue view and activity view](https://github.com/AIR-FOI-HR/AIR19E1/commit/eb343ea8744e8ac4b1be8a505abf7920b0e2207c).
- [Minor tweaks and fixes in relation with the Activity View and Profile Fragment](https://github.com/AIR-FOI-HR/AIR19E1/commit/ee33ce1fafa20116c74be0d7724d6a4dbd6d1d27).

In charge of the review: @OndrejJarina.

**Comment by pablomf97** [comment]
When a user clicks on an activity that takes place in certain sport venue, the application will show:
- The image and name of the venue.
- Information of the activity (date, creator, type of players needed and price).

![photo_2019-12-15_21-50-34.jpg](https://images.zenhubusercontent.com/5dbef2805fcf0b000185182a/9508010a-99f2-4787-9eca-c16ee02914d8)

*Please note that the data showed in the screenshot is just mock data for testing purposes and, thus, will not be shown in the final version of the project*
