### ISSUE TITLE
Implement full-text search

### ISSUE THREAD

**Issue by pablomf97** [AIR-FOI-HR/AIR19E1#32]
Implement full-text search in *Search for venues* to make it easier for the user to find a specific sport venue.

**Comment by OndrejJarina** [comment]
![81958184_1412449455593827_2147526193946034176_n.jpg](https://images.zenhubusercontent.com/5dbef27f7b4f63000158f8d5/c8597584-4669-4110-9fdc-bf63680d5706)

**Comment by OndrejJarina** [comment]
Review: @pablomf97
