### ISSUE TITLE
List of activities in any selected venue

### ISSUE THREAD

**Issue by OndrejJarina** [AIR-FOI-HR/AIR19E1#9]
Shows a list of all activities in a venue created by other users. Can list them by date, will not show past activities

**Comment by pablomf97** [comment]
**In review**: check this [commit](https://github.com/AIR-FOI-HR/AIR19E1/commit/eb343ea8744e8ac4b1be8a505abf7920b0e2207c) to review it.

In charge of the review: @OndrejJarina.

**Comment by pablomf97** [comment]
Once the user selects a venue, the application will show:
- The image of the venue.
- The name of the venue and its latitude and longitude.
- The list of activities that take place in the venue.

![photo_2019-12-15_21-50-27.jpg](https://images.zenhubusercontent.com/5dbef2805fcf0b000185182a/67a14eab-f750-40f2-856e-f7e617a452fa)

*Please note that the data showed in the screenshot is just mock data and, thus, will not be shown in the final version of the application*
